[2단계 - 행운의 로또미션] 지그(송지은) 미션 제출합니다
woowacourse/react-lotto pull request #21
Opened 2021-04-19 06:03 UTC by zigsong

안녕하세요 제이비님!
로또 미션을 함수형 컴포넌트로 바꿔 구현해보았습니다.
이번에도 꼼꼼한 리뷰 부탁드리겠습니당 🤗

### [데모 페이지](https://react-lotto-zig.netlify.app/)

### 👾 수정한 부분
1. `PriceInput` 컴포넌트가 mount되면 input에 바로 focus가 가게끔 해주었습니다.
2. `ResultModal` table의 형태를 미리 정의한 `RANK_TABLE`을 통해 loop을 도는 형태로 리턴해주었습니다.

### 🤔  궁금한 점
**Q1.**
functional component로 작성할 때, regular function과 arrow function 중에서 어떤 것을 주로 사용하시는지 궁금합니다!
마이그레이션을 하기 전에 여러 곳을 찾아보았는데, arrow function은 hoisting에서 문제가 발생할 수 있고 `return` 키워드를 생략할 수 있다는 점만 제외하면 성능 상의 차이가 없고, 대부분은 코드를 작성하는 개발자나 팀의 스타일이라고 합니다.
현재 한 파일에서 여러 개의 component를 정의하는 일은 없어서 arrow function을 사용해도 무방하겠지만, 가장 클래식한 방법(?)으로 시작해보고 싶어서 regular한 형태로 component를 작성해 보았습니다.
혹시 이에 대해 어떤 의견이 있으시면 말씀 부탁드리겠습니다! 🙇‍♂️

```javascript
// regular
function App() { } 

// arroaw
const App = () => { } 
````

2021-04-20 01:21 UTC, jbee37142 commented
> Q1. 혹시 이에 대해 어떤 의견이 있으시면 말씀 부탁드리겠습니다! 🙇‍♂️

스타일 차이라고 생각해요~

> Q2.

그래서... 질문이 뭔가요?

2021-04-20 01:31 UTC, JaeYeopHan requested changes

2021-04-20 01:31 UTC, JaeYeopHan commented on src/App.js
> +  const createLottos = () => {
이 함수의 시그니처에는 아무런 input을 받도록 되어있지만 내부 구현을 보면 `price`라는 input이 존재합니다.
이것이 어떤 문제를 발생시키고 어떻게 해결할 수 있을까요?

2021-04-20 01:31 UTC, JaeYeopHan commented on src/App.js
> +  };
`price`로 로또를 바로 생성하지 않고 useEffect에서 생성하는 이유가 뭔가요?

2021-04-20 01:31 UTC, JaeYeopHan commented on src/App.js
> +  };
모달을 띄우는데 왜 명령형으로 winningNumbers를 set해줘야 하나요? 모달에서 winningNumbers state를 보고 있고 어떤 액션에 의해 winningNumbers가 관리되고 모달을 띄우는 함수는 모달을 띄우는 역할만 해야할 것 같아요! (마치 closeResultModal 처럼요!)

2021-04-20 01:31 UTC, JaeYeopHan commented on src/components/PriceInput/index.js
> +  });
모든 렌더링마다 input에 focus하는건가요?

2021-04-20 01:31 UTC, JaeYeopHan commented on src/components/PriceInput/index.js
> +  const errorNotification = isValidPriceUnit ? null : <InputErrorMessage>{errorMessage}</InputErrorMessage>;
`errorMessage`가 `null`임을 판단해도 충분하지 않나요? `isValidPriceUnit`이 flag state가 또 필요한 이유가 있어요?

2021-04-20 01:31 UTC, JaeYeopHan commented on src/components/ResultModal/index.js
> +  };
다른 곳에서 Modal이라는 컴포넌트를 또 쓴다면 이 핸들러가 또 반복될 것 같은데, 재사용가능한 컴포넌트로 분리해보면 좋지 않을까요?

2021-04-21 01:57 UTC, zigsong commented on src/App.js
> +  const createLottos = () => {
> 아무런 input을 받도록 되어있지만

아무런 input을 받지 않도록.. 의 오타겠죠?? 
class component에서 `price`의 값을 state에 반영해준 이후 `createLottos`를 호출하기 위해
```jsx
this.setState({ price }, this.createLottos);
```
위와 같이 작성했던 것을 함수 컴포넌트로 옮기다보니
아래와 같이 작성하게 되었고,
```jsx
 useEffect(() => {
    createLottos();
  }, [price]);
```

그러다보니 `createLottos` 함수 바디의 `price`가 당연히 제대로 들어올 것이라고 생각해 버렸네요..
`price`값이 없거나 올바르게 갱신되지 않았을 때의 예외처리를 해주면 될까요?? 😮
일단 수정해보았습니다!

2021-04-21 02:06 UTC, zigsong commented on src/App.js
> +  };
`price`값을 `state`에 저장한 후 해당 `state`값을 사용하고 싶어서,
`state`의 `price`값이 갱신되었을 때 `createLottos`를 실행하도록 하였습니다.

다시 생각해보니 `PriceInput`에서 인풋 값으로 받은 `price`를 바로 사용한 후 `price` 값을 `state`에 반영시켜줘도 좋을 것 같아 수정하였습니다!

2021-04-21 02:25 UTC, zigsong commented on src/App.js
> +  };
저와 페어도 해당 메소드의 네이밍에 대해서 고민이 많았는데.. 질문 올리는 것을 잊었습니다! 😭
`WinningNumbersContainer`에서 `submit` 이벤트 발생 시 `App.js`의 `winningNumbers` state도 갱신해줘야 하고,
동시에 modal도 띄워주는 2가지 역할을 해야 해서 `WinningNumbersContainer`에서 2가지 동작을 모두 `props`로 받아 실행하도록 수정해보았습니다.

2021-04-21 02:32 UTC, zigsong commented on src/components/PriceInput/index.js
> +  });
`useEffect`의 dependency에 빈 배열 `[]`을 넣어주면 `PriceInput`이 처음 마운트되는 시점에서만 `focus`가 되어서, 다시 시작하기를 눌렀을 때 `focus`가 되지 않아 deps를 빼놨었습니다.
그런데 현재 모달이 열리고 닫히는 시점에도 해당 effect가 발생하고 있음을 인지하지 못했습니다. 

앱의 흐름상 `priceInput`의 `isDisabled` props가 바뀔 때에만 `focus`를 바꿔주면 effect 호출 시점을 알맞게 조절할 수 있음을 발견하여 `useEffect`의 deps에 `isDisabled`를 넣어주었습니다.

2021-04-21 02:34 UTC, zigsong commented on src/components/PriceInput/index.js
> +  const errorNotification = isValidPriceUnit ? null : <InputErrorMessage>{errorMessage}</InputErrorMessage>;
아하 그러네요..! 감사합니다 🤓

2021-04-21 02:35 UTC, zigsong commented on src/components/PriceInput/index.js
> +  const errorNotification = isValidPriceUnit ? null : <InputErrorMessage>{errorMessage}</InputErrorMessage>;
`WinningNumbersContainer` 역시 `errorMessage`가 `null`임을 판단해도 충분할 것 같아 똑같이 수정했습니다!

2021-04-21 03:08 UTC, zigsong commented on src/components/ResultModal/index.js
> +  };
앱의 확장성을 고려하지 못한 것 같습니다.
`Modal` 컴포넌트와 `Result` 컴포넌트로 분리해보았습니다!

2021-04-21 09:58 UTC, zigsong reviewed
리뷰 주신 코멘트들에 답글로 수정 내용 작성했습니다.
처음 PR body에 올린 2번은 질문이 아니라 그냥 이런 시도를 해봤다, 정도의 설명이었는데
제가 헷갈리게 작성해놓은 것 같네요.

피드백 반영 내용 확인 부탁드립니다!

2021-04-21 09:58 UTC, zigsong commented on src/App.js
> +    const count = price / Lotto.PRICE_UNIT;
[피드백 링크](https://github.com/woowacourse/react-lotto/pull/21#discussion_r617148079)

2021-04-21 09:58 UTC, zigsong commented on src/components/WinningNumbersContainer/index.js
> +    onOpenModal();
[피드백 링크](https://github.com/woowacourse/react-lotto/pull/21#discussion_r617155686)

2021-04-21 09:58 UTC, zigsong commented on src/components/PriceInput/index.js
> +  }, [isDisabled]);
[피드백 링크](https://github.com/woowacourse/react-lotto/pull/21#discussion_r617158119)

2021-04-21 09:58 UTC, zigsong commented on src/components/PriceInput/index.js
> +          {errorMessage && <InputErrorMessage>{errorMessage}</InputErrorMessage>}
[피드백 링크](https://github.com/woowacourse/react-lotto/pull/21#discussion_r616280407)

2021-04-21 09:58 UTC, zigsong commented on src/components/WinningNumbersContainer/index.js
> +        {errorMessage && <InputErrorMessage>{errorMessage}</InputErrorMessage>}
[피드백 링크](https://github.com/woowacourse/react-lotto/pull/21#discussion_r616280407)

2021-04-21 09:58 UTC, zigsong commented on src/App.js
> +        <LottoResult price={price} lottos={lottos} winningNumbers={winningNumbers} onResetGame={resetGame} />
[피드백 링크](https://github.com/woowacourse/react-lotto/pull/21#discussion_r616280837)

2021-04-21 11:14 UTC, JaeYeopHan approved these changes
수고하셨습니다! 👍 
리액트 미션 동안 컴포넌트에 대해 계속 고민해보면 좋을 것 같아요~~~

2021-04-21 11:14 UTC, merged

2021-04-24 09:22 UTC, zigsong commented
# 학습로그

## useRef
- DOM element를 조작하는 경우가 아닐 때에도 사용한다
- 컴포넌트의 전 생애주기를 통해 유지되는 값에 사용한다. `useRef`로 관리하는 변수는 값이 바뀌어도 컴포넌트가 리렌더되지 않는다
- `useRef`는 `.current` 프로퍼티에 변경 가능한 값을 담고 있는 “상자”와 같습니다
- 링크
    - <https://ko.reactjs.org/docs/hooks-reference.html#useref>

## useEffect 안에서 비동기 함수 호출하기 ([ref](https://github.com/zigsong/react-lotto/blob/1d274df40c00a02d328f78771f851fc6f5a09e92/src/components/AnnounceTimer/index.js))

```jsx
const [currentTime, setCurrentTime] = useState({ minutes: 10, seconds: 0 });

useEffect(() => {
  const timer = setTimeout(() => timePass(), 1000);
  const { minutes, seconds } = currentTime;

  if (minutes === 0 && seconds === 0) clearTimeout(timer);

  return () => clearInterval(timer);
}, [currentTime]);
```

## 기타
- 앱의 확장성 고려하여 재사용 가능한 컴포넌트 분리하기 ([ref](https://github.com/woowacourse/react-lotto/pull/21#discussion_r616280837))