[1단계 - 행운의 로또미션] 동동(김동희) 미션 제출합니다.
woowacourse/react-lotto pull request #24
Opened 2021-04-19 15:05 UTC by bigsaigon333

@JaeYeopHan  님 안녕하세요! 동동(김동희)입니다.  1단계 - 행운의 로또미션 제출합니다!

## 1.  [:fire: 데모사이트 :fire: ](https://bigsaigon333.github.io/react-lotto/)

## 2. [:airplane: VSCODE  in web :airplane: ](https://github1s.com/bigsaigon333/react-lotto/tree/step1)

## 3. 구현한 기능 목록 - 1단계
- [x] `Class Component`를 사용합니다.
- [x] 로또 구입 금액을 입력하면, 금액에 해당하는 로또를 발급해야 한다.
- [x] 로또 1장의 가격은 1,000원이다.
- [x] 소비자는 **자동 구매**만 할 수 있다.
- [x] 복권 번호는 번호보기 토글 버튼을 클릭하면, 볼 수 있어야 한다.
- [x] 결과 확인하기 버튼을 누르면 당첨 통계, 수익률을 모달로 확인할 수 있다.
- [x] 로또 당첨 금액은 고정되어 있는 것으로 가정한다.
- [x] 다시 시작하기 버튼을 누르면 초기화 되서 다시 구매를 시작할 수 있다.

## 4. 🔎 데모 gif
<img src="https://user-images.githubusercontent.com/61097373/115213587-a0093600-a13c-11eb-802f-f76b53805af1.gif" width="480">

2021-04-19 15:22 UTC, bigsaigon333 commented
### 질문1
디자인적인 부분을 조금 더 신경쓰고 싶었으나, 너무 일정이 지체되고 있어서 적당한 선에서 마무리하였습니다... 
CSS는 정말 체계없이 try - fail - retry 방식으로 작성중입니다.. 
CSS는 내부 로직보다 시각적으로 잘 보여지기만 하면 일단 OK라고 생각하고 넘어가는 경향이 큰 것 같습니다.
**뭔가 체계적으로 CSS를 배울 수 있는 방법이 혹시 있다면 추천해주실 수 있을까요?**
  
CSS 각각의 property는 하나하나씩 배워가고 있는데, 중복되는 css를 제거하는 방법,  유지보수가 하기 좋게끔 CSS를 작성하는 방법 등을 잘 모르겠습니다. 
BEM, OOCSS 등의 개념은 알고 있긴 합니다만... 단순히 네이밍 컨벤션 정도로만 생각하고 겉핥기식으로 조금 도입하려고 하다가 시간적 여유가 없어서 포기하고 그러기를 반복하는 것 같습니다...
**BEM, OOCSS 등을 좀더 깊게 파볼까요?**
  
SASS 등 CSS pre-processor 를 사용하면 어느 정도 해결된다고 한다고 하여도,  CSS 기저에 깔린 철학을 알고 싶습니다...
  
너무 떠먹여 달라는 질문인 것 같은데, 참고할만한 키워드나 홈페이지, 책자 정도 공유해주시면 감사하겠습니다! :bow: :bow: :bow:

2021-04-19 15:23 UTC, bigsaigon333 commented
### 질문 2  (바보같은 질문 하나 더 추가해봅니다...)
HTML, CSS, JS, UI/UX 등 모두 프론트엔드 개발자의 소양으로 당연히 갖추어야 할 것이지만, 
굳이 정량적으로 비중을 나눈다면 각각을 어느 정도 중요도를 가지고 공부하면 좋을까요?
제가 CSS를 더 공부해야겠다고 느낀 것은, 시각적으로 보여지는 것을 원하는 대로 구현해내었을때의 만족감(?), 성취감(?)이 가장 크기 때문입니다 ㅎㅎ... 
딱히 정해진 비중은 없고, 그냥 하고 싶은거 위주로 해도 된다고 말씀해주실걸로 감히 예상해보지만, 한번 더 여쭈어봅니다 :laughing:

2021-04-20 01:50 UTC, JaeYeopHan requested changes
수고하셨습니다~

---

> 질문 1.

CSS는 Cascading Style Sheets 입니다 😄 
책으로 공부해본 적은 없고 (최근에 CSS 완벽가이드 란 책이 나온 것 같은데 읽어보진 못했네요)
잘 만들어진 디자인 시스템 오픈소스들은 스타일링을 어떻게 하고 있는지 살펴보면 큰 도움이 되실 거라 생각합니다.

> 질문 2.

전부요!ㅋㅋㅋㅋ 질문이 모호해서 무슨 답변을 드려야 할지 잘 모르겠네요 ㅎㅎ 진로나 성장에 대해 고민되는 부분이 있으면 DM주세요~

2021-04-20 01:50 UTC, JaeYeopHan commented on .vscode/settings.json
> +  },
이거 너무 중요한데 아주 짱입니다 👍

2021-04-20 01:50 UTC, JaeYeopHan commented on src/App.jsx
> +      ' ': () => this.resetState(),
`' '`가 뭐예요...????

2021-04-20 01:50 UTC, JaeYeopHan commented on src/components/Modal.jsx
> +  const handleCloseClick = props.close;
props를 다시 정의한 이유가 있나요?

2021-04-20 01:50 UTC, JaeYeopHan commented on src/components/Modal.jsx
> +      Array.from({ length: winningTable.length }, () => 0)
`Array.prototype.fill`?

2021-04-20 01:50 UTC, JaeYeopHan commented on src/components/Modal.jsx
> +          tabIndex="-1"
이건 왜 -1로 해두신건가요?

2021-04-20 01:50 UTC, JaeYeopHan commented on src/components/Modal.jsx
> +        <div
button element가 더 어울리지 않을까요?

2021-04-20 01:50 UTC, JaeYeopHan commented on src/components/Modal.jsx
> +        <h2 className="text-2xl font-semibold text-center mb-4">
Modal 역할과 Result를 뿌려주는 부분이 함께 있는가 각각의 컴포넌트로 나눠주면 어떨까요?

2021-04-20 01:50 UTC, JaeYeopHan commented on src/components/Modal.jsx
> +          {' 당첨 통계 '}
이상한 띄어쓰기가 있는데 스타일 이슈라고 생각되네요? 이런 부분은 스타일로 해결을 해야 할 것 같아요;;ㅎㅎㅎ

2021-04-20 01:50 UTC, JaeYeopHan commented on src/components/WinningNumberForm.jsx
> +        return '';
switch-case statement의 의도에 맞지 않는 syntax라고 생각됩니다!

2021-04-20 01:50 UTC, JaeYeopHan commented on src/components/WinningNumberForm.jsx
> +  }
너무 거대하다고 생각되는데, 컴포넌트의 핸들러 또는 메소드로 정의를 해야 하는가 고민해보시고 컴포넌트를 의미에 맞게 나눌 수 없나? 도 고민해보시면 좋을 것 같아요~

2021-04-21 13:24 UTC, bigsaigon333 commented on src/components/Modal.jsx
> +          {' 당첨 통계 '}
a11y eslint plugin을 적용하면서 이모지를 span tag로 감쌌습니다. 
이로 인해 텍스트와 이모지 사이의 간격을 조정하기 위해 공백문자를 넣었는데, 
말씀해주신대로 이는 스타일의 문제이므로 css로 해결해야되는 거네요 ㅎㅎ...

아무 생각없이 넘어갈 뻔했는데, 짚어주셔서 감사합니다~ :+1:

2021-04-21 13:29 UTC, bigsaigon333 commented on src/components/Modal.jsx
> +  const handleCloseClick = props.close;
eslint-plugin-react plugin을 적용하였는데, 이벤트 핸들러의 prefix 를 handle로 하지 않으면 계속 에러가 나서 별 고민없이 위와 같이 코드를 작성하였습니다..

해당 eslint  룰의 페이지를 방문해서 찬찬히 읽어보다 보니 해당 룰의 의미를 깨닫게 되었습니다.
- 컴포넌트에서 자체적인 핸들러를 정의할 때는 handle prefix를 붙인다.
- 부모 컴포넌트로부터 핸들러를 props로 전달받을 때에는 on prefix 로 핸들러를 전달받는다.


이를 적용하여 수정하였습니다! :congratulations: 

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-handler-names.md

2021-04-21 13:31 UTC, bigsaigon333 commented on src/components/Modal.jsx
> +  const handleCloseClick = props.close;
# :hand:
한가지 궁금한 것은, 메소드 이름을 보았을때 메소드가 의미하는 바를 명확히 하고 싶어서  
메소드를 정의할 때는 메소드 이름을 `resetState`로 하고, `constructor`에서 bind할 때
`this.handleResetClick = this.resetState.bind(this);`  와 같이 하였는데, 이렇게 하는 건 일반적이지 않은 걸까요?

2021-04-21 13:43 UTC, bigsaigon333 commented on src/components/Modal.jsx
> +      Array.from({ length: winningTable.length }, () => 0)
아.... 이런 간결한 방법이 있었군요!! 
jbee님 덕분에 고급 메소드를 또 배워갑니다~!!! :+1:

2021-04-21 14:10 UTC, bigsaigon333 commented on src/App.jsx
> +      ' ': () => this.resetState(),
`' '` 는 spacebar를 눌렀을 때를 특정하기 위한 `event.key` 였습니다...

UX를 곰곰히 고민해보았을때 모달이 떠있을때 spacebar를 누르면 다시 시작하기 버튼이 눌리게 하는 것이 그닥 UX향상에 도움이 되지 않는 것 같아서, 해당 코드는 삭제하였습니다~ :tada:

2021-04-22 16:00 UTC, bigsaigon333 commented on src/components/Modal.jsx
> +          tabIndex="-1"
키보드 tab으로 이동하여 div.modal-close 에 접근한 경우, 테두리를 표시하는 시각적 효과를 주고 싶었습니다.
이를 구현하는 방식으로 svg에 시각적 효과를 주고 div.modal-close는 포커스가 되지 않도록 하는 잘못된 방법을 사용하였습니다.

말씀해주신대로 button element 로 수정하니 원하는 바를 쉽게 달성할 수 있었습니다! 감사합니다~! :bowing_man:

2021-04-22 16:00 UTC, bigsaigon333 commented on src/components/Modal.jsx
> +        <div
https://github.com/woowacourse/react-lotto/pull/24#discussion_r616285384

2021-04-22 16:08 UTC, bigsaigon333 commented on src/components/Modal.jsx
> +        <h2 className="text-2xl font-semibold text-center mb-4">
Result를 뿌려주는 부분을  WinningResult.jsx 로 추출하였습니다! 
관심사의 분리(?)를 적용한 것 같아 뿌듯하네요 :smile:

2021-04-22 16:19 UTC, bigsaigon333 commented on src/components/WinningNumberForm.jsx
> +        return '';
switch 구문은 각 조건 중 하나만 일치하여야 하는, 즉 각 조건의 병렬성이 충족되어야 하는 것으로 이해하고 있습니다.
위의 validation message  산정시의 조건들은 두 개 이상의 참이 존재할 수 있어 병렬이 아니며, 제가 부여한 우선순위가 존재하므로 switch 구문에는 맞지 않는 것으로 이해하였습니다!

따라서 if문 - early return 으로 수정하였습니다 :laughing:

2021-04-25 10:02 UTC, bigsaigon333 commented on src/App.jsx
> +      ' ': () => this.resetState(),
https://github.com/woowacourse/react-lotto/pull/24/commits/85536be174e8c8ccac22a9d0f0d03a061759e586

2021-04-25 10:03 UTC, bigsaigon333 commented on src/components/Modal.jsx
> +  const handleCloseClick = props.close;
관련 커밋입니다: https://github.com/woowacourse/react-lotto/pull/24/commits/8ae15b458cc4cfa737659598d8b2a316b6525679

2021-04-25 10:03 UTC, bigsaigon333 commented on src/components/Modal.jsx
> +      Array.from({ length: winningTable.length }, () => 0)
https://github.com/woowacourse/react-lotto/pull/24/commits/3f1a27af7bbdc5d1687e2bc1fc71664afe285d95

2021-04-25 10:03 UTC, bigsaigon333 commented on src/components/Modal.jsx
> +          tabIndex="-1"
https://github.com/woowacourse/react-lotto/pull/24/commits/da4733a5f669cd068a75e42faab267cf9cc2c3b6

2021-04-25 10:03 UTC, bigsaigon333 commented on src/components/Modal.jsx
> +        <div
https://github.com/woowacourse/react-lotto/pull/24/commits/da4733a5f669cd068a75e42faab267cf9cc2c3b6

2021-04-25 10:03 UTC, bigsaigon333 commented on src/components/Modal.jsx
> +        <h2 className="text-2xl font-semibold text-center mb-4">
https://github.com/woowacourse/react-lotto/pull/24/commits/962b99b08b695dd4b13c3e40fd323b24553535db

2021-04-25 10:04 UTC, bigsaigon333 commented on src/components/Modal.jsx
> +          {' 당첨 통계 '}
https://github.com/woowacourse/react-lotto/pull/24/commits/40bdfb90873d3c8f1083668545f509d2911f9086

2021-04-25 10:04 UTC, bigsaigon333 commented on src/components/WinningNumberForm.jsx
> +        return '';
https://github.com/woowacourse/react-lotto/pull/24/commits/4ee81016a5c286d93fefd5db87457814ca239fd5

2021-04-25 10:07 UTC, bigsaigon333 commented on src/components/WinningNumberForm.jsx
> +  }
validator의 경우 각 input의 값들을 전달받아서 계산할 수 있으므로, 굳이 컴포넌트 내에 위치할 필요가 없다고 판단하여, util함수로 분리하였습니다! (https://github.com/woowacourse/react-lotto/pull/24/commits/28265b3f2ef0ec2efa157067f9b5281d6acf8ae8)

또한 당첨번호 입력란과 보너스 번호 입력란의 input tag가 중복되므로, NumberInput 이라는 컴포넌트로 분리하였습니다!(https://github.com/woowacourse/react-lotto/pull/24/commits/61ee557f714b29b967a6bc1d811eb682157e5d0e) 


Top-Down 방식으로 프로그램을 작성하여서, 컴포넌트 분리가 거의 되지 않았었습니다. 이번에 NumberInput 컴포넌트를 추출하면서,  이런 input 태그는 재사용이 가능하니까 컴포넌트를 분리하면 좋겠구나! 라는걸 느낄 수 있어서 좋았습니다 :smile: (https://github.com/woowacourse/react-lotto/pull/24/commits/2c2dc4ae4368b44c03d087f9d04117a2ff1980bd)

2021-04-25 10:13 UTC, bigsaigon333 commented
궁금한 점이 있습니다!
event handler가 수행하는 기능을 명확히 이름으로 드러내는 것과, 
event handler에는 handle prefix를 붙이는 컨벤션이 충돌하는 것처럼 생각되었습니다. 

따라서 이를 절충해서 
reset버튼을 클릭하였을때 state를 초기화하는 click event handler를 아래와 같이 선언할 때에는 resetState로 정의하고, 
constructor에서 bind할 때는  `this.handleResetClick = this.resetState.bind(this);` 와 같이 하였는데, 이렇게 하는 건 일반적이지 않은 걸까요?


- 선언할 때:  
```jsx
  resetState() {
    this.setState(...this.initialState);
  }
```
- constructor에서 bind할 때
 ```jsx
  constructor(props) {
    // ...
    this.handleResetClick = this.resetState.bind(this);
  }
```

https://github.com/woowacourse/react-lotto/pull/24#discussion_r617534637

관련 커밋입니다: https://github.com/woowacourse/react-lotto/pull/24/commits/8ae15b458cc4cfa737659598d8b2a316b6525679

2021-04-25 10:17 UTC, bigsaigon333 commented
> 질문 1.
CSS는 Cascading Style Sheets 입니다 smile
책으로 공부해본 적은 없고 (최근에 CSS 완벽가이드 란 책이 나온 것 같은데 읽어보진 못했네요)
잘 만들어진 디자인 시스템 오픈소스들은 스타일링을 어떻게 하고 있는지 살펴보면 큰 도움이 되실 거라 생각합니다.


Chakra UI 를 많이 추천해주시는 것 같던데, 여러  디자인 시스템 오픈소스들을 연구해보도록 하겠습니다! :bowing_man: 


>질문 2.
전부요!ㅋㅋㅋㅋ 질문이 모호해서 무슨 답변을 드려야 할지 잘 모르겠네요 ㅎㅎ 진로나 성장에 대해 고민되는 부분이 있으면 DM주세요~

ㅎㅎ... 우문현답이네요 ㅎㅎ.. 요즘 조금 더 자신만의 색깔을 찾아가자고 생각해서 여러 고민들을 하고 있는데, 
추후 저의 생각들이 정리가 되고 여쭤볼게 생기면, 잘 정리해서 연락 드릴수 있도록 하겠습니다~! 
바쁘신데도 DM 달라고 흔쾌히 말씀해주셔서 정말 감사드립니다 :+1:  역시 갓제이비 :bee:

2021-04-25 11:17 UTC, JaeYeopHan commented on src/components/Modal.jsx
> +  const handleCloseClick = props.close;
~함수 컴포넌트에선 bind 할 일이 없긴 한데,~
bind만 해주는 데 이름이 달라서 읽기가 더 힘들어지진 않을까요?
케바케이긴 하겠지만! resetState 경우, 그 코드가 복잡하지도 않을 것 같아서 handleResetClick에서 정의를 해줘도 괜찮아보이네요 ㅎㅎ

2021-04-25 11:18 UTC, JaeYeopHan commented on src/components/Modal.jsx
> +        <h2 className="text-2xl font-semibold text-center mb-4">
앗, Modal에서 Result 뿌려주는 부분을 단순히 추출만 하는 것으론 Modal 컴포넌트를 재사용할 수 없어보이는데요, 요건 동동님이 좀 더 고민해보면 좋을 것 같아서 코멘트만 하고 넘어갑니다~

2021-04-25 11:20 UTC, JaeYeopHan approved these changes
수고하셨어요~
코멘트 2개 더 남겼는데 확인만 해보세요~

2021-04-25 11:20 UTC, merged