[2단계 - 행운의 로또미션] 동동(김동희) 미션 제출합니다.
woowacourse/react-lotto pull request #54
Opened 2021-04-29 03:05 UTC by bigsaigon333

@JaeYeopHan 님 안녕하세요! 동동(김동희)입니다.

2단계 - 행운의 로또미션 제출합니다!

## 1.  [:fire: 데모사이트 :fire: ](https://bigsaigon333.github.io/react-lotto/)

## 2. [:airplane: VSCODE  in web :airplane: ](https://github1s.com/bigsaigon333/react-lotto/tree/step2)

## 3. 구현한 기능 목록 - 2단계

- [x] Step1의 `Class Component`를 `Function Component`로 마이그레이션 합니다.

2021-04-29 07:32 UTC, bigsaigon333 commented
## 질문 있어요 :hand: 

Class Component 일 때는 `this.state = {a: 1, b: 2}` 이런 식으로 state라는 하나의 객체에 담겨있었는데,
Function Component로 마이그레이션 하면서 아래와 같이 각 프로퍼티를 분리하였습니다.
```jsx
const [a, setA] = useState(1);
const [b, setB] = useState(2);
```
a와 b가 직접적인 관련이 없다면, 각각 관리하는 것이 맞다고 저는 판단하였는데요, 
혹시 이러한 상황에서 일반적인 리액트 컨벤션(?)이 있는지 궁금합니다!

2021-04-29 12:14 UTC, JaeYeopHan requested changes
코멘트했어요~
'컴포넌트'가 무엇인지 좀 더 고민해보면 좋겠습니다!

---

> a와 b가 직접적인 관련이 없다면, 각각 관리하는 것이 맞다고 저는 판단하였는데요, 혹시 이러한 상황에서 일반적인 리액트 컨벤션(?)이 있는지 궁금합니다!

컨벤션(?) 같은 건 없습니다~ 
직접적인 관련이 없다면, 각각 관리하는 것이 맞지 않을까요?

2021-04-29 12:14 UTC, jbee37142 commented on src/App.jsx
> +    const isOpen = [tickets.length > 0, winningNumbers.length > 0, bonusNumber > 0].every(Boolean);
그냥 `&&` 인 것 같은데 ㅋㅋㅎㅋㅎ 신박하네요

2021-04-29 12:14 UTC, jbee37142 commented on src/App.jsx
> +    setIsModalOpen(false);
`const defaultValue = { ... }`
요렇게 해줘도 괜찮을 것 같네요

2021-04-29 12:14 UTC, jbee37142 commented on src/App.jsx
> +  const handleResetClick = () => {
모든 크루 분들이 reset을 이렇게 하시던데, 그냥 다시 mount 시켜버려도 됩니당 ㅋㅋㅋ

2021-04-29 12:14 UTC, JaeYeopHan commented on src/components/CloseButton.jsx
> +    <button
button element에 다른 attribute를 넘겨줘야 하는 상황이 발생하면 매번 props가 추가로 정의되어야 하는 확장성 없는 컴포넌트가 되어버렸는데요, 어떻게 하면 이 CloseButton을 사용하는 입장에서 좀 더 사용성을 높일 수 있을까요?

2021-04-29 12:14 UTC, JaeYeopHan commented on src/components/Modal.jsx
> +  const ref = React.createRef();
useRef와의 차이점을 알아보면 좋을 것 같아요~

2021-04-29 12:14 UTC, JaeYeopHan commented on src/components/Modal.jsx
> +      tabIndex="-1"
왜 tabIndex=-1 을 해주셨나요?

2021-04-29 12:14 UTC, JaeYeopHan commented on src/components/WinningNumberForm.jsx
> +  });
👀  혹시 이 코드 작성하면서 이상하다는 생각 안 드셨는지요!ㅎㅎㅎ

2021-05-03 07:14 UTC, bigsaigon333 commented on src/App.jsx
> +    const isOpen = [tickets.length > 0, winningNumbers.length > 0, bonusNumber > 0].every(Boolean);
&& 로만 적으면 가독성이 좋지 않다고 생각했으며, 추후에 다른 조건들이 추가될 수 있다는 뉘앙스(?)를 남기고 싶어서 위와 같은 형식으로 작성해보았습니다 ㅎㅎ

2021-05-03 07:17 UTC, bigsaigon333 commented on src/App.jsx
> +    setIsModalOpen(false);
하드코딩되어 있던 각 상태의 초기값을  별도의 상수(defaultValue)로 추출하여, 유지보수가 용이하게 하였습니다! :laughing: 


관련 커밋입니다: https://github.com/woowacourse/react-lotto/pull/54/commits/4a22551bbfbad9fb350ad7e3bbdb199cf9ce75cd

2021-05-03 07:25 UTC, bigsaigon333 commented on src/App.jsx
> +  const handleResetClick = () => {
이런 간단한 방법이 있다니...!! :bee: :+1: 

다시 mount 하는 방법을 생각해보았습니다...

### 1) unmountComponentAtNode() && render()

```jsx
const handleResetClick = () => {
  const $root = document.querySelector("#root");

  ReactDOM.unmountComponentAtNode($root);
  ReactDOM.render(<App />, $root);
}
```

아무리 생각해봐도 이거는 의도하신 바가 아닌 것 같다는 생각과,
ReactDOM 을 건드리는 곳이 index.jsx 외에 또 있다면  추후에 유지보수시에 굉장히 어려울 것 같다는 생각이 들었습니다.

### 2) Lotto Component를 추출하여 key를 변경하는 방법

App Component의 바로 밑에 바로 구매금액 입력란, 당첨번호 입력란 등의 Component가 있는데,

App Component와 다른 Component  사이에 Lotto Component를 위치시킨 후, 

다시 시작하기 버튼을 누르면 Lotto Component의 key를 변경하게 하여 Lotto Component를 다시 mount시켜, 

Lotto의 상태를 초기화시켰습니다. 


클래스 Component는 생명주기가 비교적 제 머리속에서 잘 정리가 되었는데,  
함수 컴포넌트는 아직 익숙하지가 않아서 조금 애를 먹었습니다..

혹시 위의 두가지 방법 이외에도 좋은 방법이 있다면 작은 힌트 부탁드립니다 ㅎㅎ.. :love_letter: 

관련 커밋입니다: https://github.com/woowacourse/react-lotto/pull/54/commits/5f3da960c0aee11b721e32e35d4ad488a374d2a6

2021-05-03 07:32 UTC, bigsaigon333 commented on src/components/Modal.jsx
> +  const ref = React.createRef();
useRef()는 매 렌더링시에 동일한 ref object를 반환하는 반면, 
React.createRef()는 새로운 ref object를 반환하는 것을 알게 되었습니다!

해당 상황에서는 useRef를 사용하는 것이 적절하다고 생각되어 useRef를 사용하는 것으로 수정하였습니다 :smile: 

관련 커밋입니다: https://github.com/woowacourse/react-lotto/pull/54/commits/6616d90f7d2abe537ca88c20765c1d8544211789

2021-05-03 07:45 UTC, bigsaigon333 commented on src/components/Modal.jsx
> +      tabIndex="-1"
1. 모달이 열려있을 때 Escape 키를 누르면 모달이 닫히는 기능을 구현하고 싶었습니다.

2. 기존에 Class Component 로 작성하였을 때는 아래와 같이 document에 직접 keyup 이벤트리스너를 설정하여 
모달이 열려있으면서 Escape 키가 눌리면 모달이 닫히게끔 하였습니다. 

```jsx
class App extends Component {

  componentDidMount() {
    document.addEventListener("keyup", handleKeyUp);
  }
  
  componentWillUnmount() {
    document.removeEventListener(handleKeyUp);
  }
}
```

3. document에 직접 이벤트리스너를 설정하여 구현하는 것은 React 스럽지 않다(?)는 피드백을 받아서 
Function Component로 migration 하면서 이 부분에 대한 고민을 해보았습니다.
제가 새로 생각한 방법은 modal 이 열리면 modal div에 keyup 이벤트리스너를 등록하는 방법이었습니다.
keyup 이벤트의 경우 focus가 있는 경우에 fire되나,  div와 같은 non-interactive element의 경우 tabIndex를 명시하지 않는 한 focus가 가지 않아,  tabIndex를 명시하고, ref를 활용하여 div에 바로 focus가 가게끔 하였습니다.

4. tabIndex를 "-1"로 준 이유는, modal div 자체는 interactive elements가 아니므로 굳이 키보드를 이용하여 접근하게 할 필요는 없다고 판단하였기 때문입니다. 

---

혹시 더 고민할 부분이 있다면 말씀해주시면 감사하겠습니다~~ :smile:

2021-05-03 08:08 UTC, bigsaigon333 commented on src/components/WinningNumberForm.jsx
> +  });
굉장히 이상하다고 생각했습니다 ㅎㅎ...

useEffect를 ids에 의존하여 호출하는 것도 이상하고, 이러한 형태의 useEffect 사용을 본 적이 없어서 이상하다고 생각했지만,

기존 코드를 최대한 살리려면 이렇게 작성하는 방법밖에 없는 것 같아서, 더 고민하지 않고 그냥 작성해버렸습니다 :sob: 

--- 
천천히 고민해보았습니다.  useEffect는 렌더링 외의 사이드 이펙트를 이용하기 위해서 사용하는 훅인데, 

다른 상태에(inputs) 의존하는 상태(validaitonMessage)를 업데이트하기 위해서 사용하는 것이 맞는 것일까? 라는 생각이 들었습니다.

onChange 핸들러를 통해 inputs가 갱신될 때, 갱신될 새로운 inputs를 바로 알 수 있으므로, 이를 통해 바로 validationMessage를 갱신하도록 수정하였습니다!

2021-05-03 08:08 UTC, bigsaigon333 commented on src/components/WinningNumberForm.jsx
> +  });
관련 커밋입니다: https://github.com/woowacourse/react-lotto/pull/54/commits/97a68d60a373aef44cdf0136ec9a18633647ad3e

2021-05-03 08:27 UTC, bigsaigon333 commented on src/components/CloseButton.jsx
> +    <button
onClick 이외의 className, type 및 다른 props들(rest parameter를 이용하여)을 받아서, button element에 넘겨주도록 하였습니다.

좀 더 유연하게 된 것 같지만, rest parameter로 다른 props들을 넘겨주는 건 CloseButton 입장에서는 정체를 모르는 props도 button element에 넘겨주게 되어, 조금 위험한 건 아닌가.. 하는 생각도 듭니다... :fearful:   

제가 제대로 이해한게 맞을까요..?

관련 커밋입니다: https://github.com/woowacourse/react-lotto/pull/54/commits/1b92eab6bd1c0ed78271278de3deb855c96345b1

2021-05-03 08:27 UTC, bigsaigon333 commented
>  '컴포넌트'가 무엇인지 좀 더 고민해보면 좋겠습니다!

컴포넌트는 재사용이 가능한 독립적인 UI 단위라고 생각합니다... 

lotto 프로젝트를 시작할 때, Top-Down 방식으로 설계를 하였고, 

처음과 끝이 명확한 프로젝트라 생각하여, 컴포넌트의 재사용에 대해서 많이 고민하지 않았던 것 같습니다..

추후 미션 진행해나가면서 '컴포넌트'에 대해서 꾸준히 고민해나가도록 하겠습니다!

2021-05-05 06:49 UTC, JaeYeopHan commented on src/App.jsx
> +    const isOpen = [tickets.length > 0, winningNumbers.length > 0, bonusNumber > 0].every(Boolean);
일단 이렇게 조건이 많으면 이게 맞나? 하는 생각부터 해보셔도 좋을 것 같아요!
너무 많은 것을 알고 있는 컴포넌트는 아닌지? 의심이 드네요!

2021-05-05 06:50 UTC, JaeYeopHan commented on src/App.jsx
> +  const handleResetClick = () => {
2번 맞아요 ㅋㅋㅋ

2021-05-05 06:52 UTC, JaeYeopHan commented on src/components/CloseButton.jsx
> +    <button
이해한 것이 맞습니다 ㅎㅎ
나머지 props에 대해서도 타이핑을 해줌으로써 정체를 모르는 props가 전달되지 않도록 컴파일 단계에서 해결할 수 있을 것 같네요~~

2021-05-05 06:53 UTC, JaeYeopHan commented on src/components/Modal.jsx
> +      tabIndex="-1"
> tabIndex를 "-1"로 준 이유는, modal div 자체는 interactive elements가 아니므로 굳이 키보드를 이용하여 접근하게 할 필요는 없다고 판단하였기 때문입니다.

div 자체는 interactive elements가 아니므로 굳이 tabIndex를 "-1"로 주지 않아도 되지 않나요?

2021-05-05 06:55 UTC, JaeYeopHan commented on src/components/WinningNumberForm.jsx
> +  });
이상하다고 생각하셔서 다행이지만 그 해결방법은 조금 아쉽네요 ㅎㅎ
그래도 전 보다 좋은 것 같아요! 👍

2021-05-05 06:55 UTC, JaeYeopHan approved these changes
수고하셨어요~

2021-05-05 06:55 UTC, merged