[2단계 - 행운의 로또미션] 피터(안현철) 미션 제출합니다.
woowacourse/react-lotto pull request #71
Opened 2021-06-14 08:05 UTC by iborymagic

조금만 더 하다가 엄청 늦어버렸네요. 죄송합니다.
일단 PR부터 제출하고나서 계속 리팩토링 해볼 생각입니다.

[2단계 로또 미션 데모 사이트](https://iborymagic-lotto.netlify.app/)

### 📁디렉토리 구조
```
│  App.js
│  index.js
│  reset.scss
│  style.scss
│
├─animation
│      coinSpin.json
│
├─components
│  ├─common
│  │  ├─Button
│  │  │      index.js
│  │  │      style.scss
│  │  │
│  │  ├─Modal
│  │  │      index.js
│  │  │      style.scss
│  │  │
│  │  ├─NumberInput
│  │  │      index.js
│  │  │      style.scss
│  │  │
│  │  └─Toggle
│  │          index.js
│  │          style.scss
│  │
│  ├─LottoBallCanvas
│  │      index.js
│  │      style.scss
│  │
│  ├─MoneyInput
│  │      index.js
│  │      style.scss
│  │
│  ├─Receipt
│  │  │  index.js
│  │  │  style.scss
│  │  │
│  │  ├─PurchaseNumberItem
│  │  │      index.js
│  │  │      style.scss
│  │  │
│  │  └─PurchaseNumberList
│  │          index.js
│  │          style.scss
│  │
│  ├─ResultModal
│  │      index.js
│  │      style.scss
│  │
│  ├─shared
│  │  └─LotteryBall
│  │          index.js
│  │          style.scss
│  │
│  ├─TimeLeft
│  │      index.js
│  │      style.scss
│  │
│  └─WinningNumber
│          index.js
│          style.scss
│
├─constants
│      message.js
│      number.js
│      palette.js
│      type.js
│
├─contexts
│      ModalContextProvider.js
│
├─sound
│      muyaho.mp3
│
└─utils
        calculatePrize.js
        colorBall.js
        makeAutoTicket.js
        randomNumber.js
        scroll.js
        validations.js
```

### 🧐 봐주셨으면 하는 부분
1. 폴더 구조가 적절한지 봐주셨으면 좋겠습니다. 
다른 곳에서도 공통적으로 사용될 만한 컴포넌트라고 생각하는 것들은 common에 넣었고,
이 프로젝트 내부에서 재사용되고 있는 컴포넌트는 shared로 따로 분류하였습니다.
그리고 가장 찝찝한 건 utils인데, 특정 도메인에 한정된 함수가 들어가 있는 상태입니다.
특정 컴포넌트에서만 사용되는 함수라면(calculatePrize, colorBall, makeAutoTicket) 
그냥 해당 컴포넌트 상단에다가 const로 선언해놓는 게 나을까요,
아니면 다른 폴더이름으로 따로 분류를 해서 거기다가 넣는 것이 좋을까요?

2. ref의 적절한 사용 여부
최대한 ref에 익숙해지기 위해 배열에 ref를 담아서 사용하기도 해보고,
forwardRef를 사용해서 자식 컴포넌트에 ref를 내려줘보기도 했습니다.
그리고 값이 유지되었으면 좋겠지만, 리렌더링은 유발하지 않았으면 좋겠는 변수도 ref를 사용했습니다.
ref를 사용한 부분들을 봐주시고, 상황에 맞게 잘 사용되었는지 봐주실 수 있나요?

감사합니다.

2021-06-16 14:17 UTC, devJang requested changes
왜 무모한 시도를 했냐며
진한 국물이 우러나올 정도로 피드백하고 혼냈던 그 프로젝트군요..

일단 50% 이상은 아직 @ddongule 의 코드와 동일하기 때문에 해당 PR https://github.com/woowacourse/react-lotto/pull/68 을 꼭 한번 참고해주세요!

또한 레벨2를 끝내고 작성한 것을 인지하고 리뷰했습니다.

## 요청하신 피드백

### 1. 폴더 구조가 적절한지 봐주셨으면 좋겠습니다.

#### 1-1. 다른 곳에서도 공통적으로 사용될 만한 컴포넌트라고 생각하는 것들은 common에 넣었고, 이 프로젝트 내부에서 재사용되고 있는 컴포넌트는 shared로 따로 분류하였습니다.

굳이 분리할 필요가 있을까.. 싶은 부분입니다만
`common`은 정말 시멘틱하게 스타일만 가지고 있는 컴포넌트
`shared`는 도메인에 결합도를 가진 컴포넌트처럼 보이네요

`shared`가 나중에 비대해진다면 어떻게 될까요?
이걸 고민해보시면 답이 나올거라 봅니다

또한 `shared`라는 네이밍이 다른 디자인 시스템이나 UI 컴포넌트들을 보면 꽤나 많이 사용되는데요
어떻게 사용되는지 조금 더 찾아보시면 그 또한 피터의 고민을 더 명확하게 해줄 것이라 봅니다.


#### 1-2. 그리고 가장 찝찝한 건 utils인데, 특정 도메인에 한정된 함수가 들어가 있는 상태입니다. 특정 컴포넌트에서만 사용되는 함수라면(calculatePrize, colorBall, makeAutoTicket) 그냥 해당 컴포넌트 상단에다가 const로 선언해놓는 게 나을까요, 아니면 다른 폴더이름으로 따로 분류를 해서 거기다가 넣는 것이 좋을까요?

저 또한 보는 내내 찝찝했답니다.
다른 크루들은 커스텀 훅을 만들거나 서비스 계층을 만들어서 분리하는 노력을 보였는데요.
어떻게하든 다 애매했습니다.

애초에 앱의 요구사항 자체가 작기 때문에 뭘 하든 애매해질 수 있거든요.

하지만.. 유틸과 어울리지 않는 것은 느끼시는 것과 마찬가지라고 봅니다.
유틸이 무엇인가 이 로직들은 도메인을 가졌는데 유틸과 어울리는 것인가 계층을 더 나눠보세요
아니면 포기하시고 몰아넣는 것도 지금보다 나을 수 있습니다.

#### 2. ref의 적절한 사용 여부

사용하고 시도해보려는 노력 자체가 아주 보기 좋았습니다.
몇가지 컴포넌트를 제외하고는 적절하게 사용하셨다는 생각이 듭니다.

몇가지 컴포넌트들은 차라리.. 리액트와 관련 없는 로직을 굳이 ref로 활용하지 않고 격리하는 방법을 고민해보시는 것도 추천합니다.

## 개인적인 피드백

몇몇 코멘트 남겼으니 꼭 봐주시고 요약해서 더 설명드리자면

### TimeLeft, LottoBallCanvas.........

설명은 생략하겠습니다. 힌트는 그루밍 PR에도 있답니다.

### 캔버스.....

그 어디에도 캔버스가 골고루 쓰이지 않습니다.
근데 여기저기 퍼져있으니 차라리 한 곳으로 모아놓는게 어떨까요?
또한 리액트에 들어갈 로직과 아닌 로직이 마구마구 리액트 컴포넌트에 짬뽕으로 들어가있습니다.
매우 시급해보이네요

### 모달...

모달을 위해 개발하신 것처럼 모달에 굉장히 큰 힘을 주셨네요
또한 모달을 `ContextAPI`로 분리하고 나눈 시도는 칭찬해주고 싶습니다.
하지만 그러다보니 `ResultModal`이 비대해졌습니다.

---

피드백만 받으시겠다면 머지하도록 할테니 따로 말씀해주세요!

2021-06-16 14:17 UTC, pocojang commented on package.json
> -  "author": "ddongule <mnk918p@gmail.com>",
good bye @ddongule ~

2021-06-16 14:17 UTC, pocojang commented on src/App.js
> +  winningInputRefs.current = [...Array(LOTTERY_NUMBERS_LENGTH)].map(
OMG........

왜 이렇게 덩그러니 나온거죠?

2021-06-16 14:17 UTC, pocojang commented on src/App.js
> +        value: 0,
`0`은 무엇일까요?

2021-06-16 14:17 UTC, pocojang commented on src/App.js
> +    }, ANIMATION.DELAY);
Good!

2021-06-16 14:17 UTC, pocojang commented on src/App.js
> +          <TimeLeft />
`App.js`면 거의 엔트리급 컴포넌트인데
여기서도 컴포넌트를 너무 날 것으로 보여주는게 아닐까요?

2021-06-16 14:17 UTC, pocojang commented on src/App.js
> +        <Lottie
Good~

2021-06-16 14:17 UTC, pocojang commented on src/components/LottoBallCanvas/index.js
> +const LottoBallCanvas = () => {
리뷰하기에는 상당히 괴로운 컴포넌트군요..
컴포넌트와 관계없이 분리할 수 있는 로직들도 마구마구 섞여있습니다ㅠㅠ

2021-06-16 14:17 UTC, pocojang commented on src/components/LottoBallCanvas/index.js
> +  let isBallDrawn = false;
매우 위험해보이네요..

2021-06-16 14:17 UTC, pocojang commented on src/components/WinningNumber/index.js
> +    ref.current[0].current.focus();
뎁스가 너무 깊다는 생각이 들지 않으신가요~?

2021-06-16 14:17 UTC, pocojang commented on src/components/WinningNumber/index.js
> +    const inputValue = Math.min(Number(e.target.value), MAX_LOTTO_NUMBER);
리액트의 상태를 사용하지 않고
굳이 이벤트에서 값을 가져와야하나요?

2021-06-16 14:17 UTC, pocojang commented on src/components/WinningNumber/index.js
> +export default React.memo(WinningNumber);
`memo`는 필요해서 사용하신게 맞을까요?

2021-06-16 14:17 UTC, pocojang commented on src/components/common/Modal/index.js
> +  const { closeModal } = useContext(ModalContext);
오 좋은 시도네요

2021-06-16 14:17 UTC, pocojang commented on src/components/common/Modal/index.js
> +    if (e.target === e.currentTarget) {
코드만 보기에는 이상한 조건 같은데
잘 동작하는군요

2021-06-16 14:17 UTC, pocojang commented on src/components/common/NumberInput/index.js
> +  <input ref={ref} className={`number-input ${customClass}`} type='number' {...rest} required />
{...rest} 를 마지막에 넣는게 좋지 않을까요~~?

2021-06-16 14:17 UTC, pocojang commented on src/constants/palette.js
> +const PALETTE = {
좋습니다~~

2021-06-16 14:17 UTC, pocojang commented on src/contexts/ModalContextProvider.js
> +import React, { createContext, useState } from 'react';
아주 멋진 시도입니다
다만 파일명과 다르게 하는 역할이 많아보입니다

2021-06-24 11:09 UTC, iborymagic commented on src/App.js
> +  winningInputRefs.current = [...Array(LOTTERY_NUMBERS_LENGTH)].map(
inputRef가 혼자 튀어나와있는 걸 말씀하시는 거라면, inputRef만 구입 금액을 입력하는 input이라서 성격이 다른 input이라 따로 빼놓은 것입니다.
winningInputRef.current를 채워넣는 로직이 바깥에 있는 것을 말씀하시는 거라면, 작성할 당시에는 따로 빼서 current에 직접 넣어주는 게 더 알아보기 편하다고 생각했는데 막상 다시보니 그냥 합치는 게 나을 것 같아서 하나로 합쳐주었습니당 😅

2021-06-24 11:12 UTC, devJang commented on src/App.js
> +  winningInputRefs.current = [...Array(LOTTERY_NUMBERS_LENGTH)].map(
`winningInputRef.current`로직을 말씀드린겁니당~
다시 합칠 필요는 없구요
해당 로지을 언제 트리거 시키는게 좋을까에 대한 의문이 들더라구요~

2021-06-24 11:16 UTC, iborymagic commented on src/App.js
> +        value: 0,
숫자의 초기값으로 0을 넣어주는 건 당연하다고 생각했는데,
생각해보니 그렇지가 않았네요. 너무 제 관점에서만 생각했습니다.
상수화해서 0의 의미를 명시해줬습니다.

2021-06-24 11:21 UTC, iborymagic commented on src/components/common/Modal/index.js
> +    if (e.target === e.currentTarget) {
'modal'이라는 클래스를 가진 엘리먼트가 화면 전체를 덮는 희미한 부분(dimmer)이고,
그 안에다가 'modal-inner'로 모달을 구현했기 때문에 가능한 조건인 것 같습니다.
'modal'에다가 이벤트를 달아줘서, 'modal-inner'가 아닌 정확히 'modal' 부분을 클릭해야만
(e.target === e.currentTarget) 모달이 닫히도록 구현해놨습니당

2021-06-24 11:21 UTC, iborymagic commented on src/components/common/NumberInput/index.js
> +  <input ref={ref} className={`number-input ${customClass}`} type='number' {...rest} required />
반영했습니다.

2021-06-24 11:23 UTC, iborymagic commented on src/components/WinningNumber/index.js
> +export default React.memo(WinningNumber);
이제는 WinningNumber를 비제어로 바꿨기 때문에 더이상 필요없는 코드가 되었네요. 지우도록 하겠습니다.

2021-06-24 11:31 UTC, iborymagic commented on src/components/WinningNumber/index.js
> +    ref.current[0].current.focus();
혹시 배열로 ref를 사용할 때, 이렇게 사용하는 방법 말고 다른 방법이 있는걸까요?
저도 가독성이 떨어진다고 생각하지만, 다른 마땅한 방법을 모르겠습니다..

2021-06-24 13:48 UTC, devJang commented on src/components/WinningNumber/index.js
> +    ref.current[0].current.focus();
`lodash`에 `first`라는 유틸 함수가 있는데 그것을 한번 참고 해보세요~
하지만 이 부분은 `current`가 두번이나 나오는게 문제라고 봅니당

2021-06-24 13:49 UTC, devJang commented on src/components/WinningNumber/index.js
> +export default React.memo(WinningNumber);
코드를 잘 파악하고 계셨군요
충분합니다!

2021-06-24 13:50 UTC, devJang commented on src/components/common/Modal/index.js
> +    if (e.target === e.currentTarget) {
아하 그랬군요
제가 너무 편협하게 코드를 봤네요!

2021-06-24 14:05 UTC, iborymagic commented on src/components/WinningNumber/index.js
> +    const inputValue = Math.min(Number(e.target.value), MAX_LOTTO_NUMBER);
input에서 값을 가져와서 상태에 저장하는 함수라서 이벤트에서 값을 가져와야 합니당

2021-06-25 08:57 UTC, iborymagic commented on src/components/LottoBallCanvas/index.js
> +  let isBallDrawn = false;
일단, 캔버스 변수, 함수 선언과 로직을 전부 useEffect 내부로 몰아넣었습니다.
그리고나서 useEffect를 hook으로 만들어서 컴포넌트로부터 분리를 하긴 했는데,
포코가 말씀하신 '리액트에 들어가면 안되는 로직'을 분리할 만한 방법을 찾지는 못했습니다.

제가 생각하기로는 rebound나 draw 등의 계산 함수들을 따로 빼라는 의미이신 것이라고 생각해서,
분리하려고 노력을 해봤는데 해당 함수들은 ball, degrees 같은 변수들을 
내부에서 직접 갖다쓰는 함수들이기때문에 해당 변수들과 떨어지면 안되는 관계입니다. 
매개변수로 받는 방법도 생각해봤는데, 매개변수로 받아야할 변수들이 너무 많아지고, 
isBallDrawn같은 경우는 객체로 감싸야할 것 같아서 함수를 분리해서 얻을 수 있는 것에 비해 
너무 많은 비효율이 따라오는 것 같습니다.

그래서 마땅한 방법을 찾지 못해, 함수 선언들과 호출들을 모두 useEffect에 몰아넣는 방법을 선택하게 됐습니다.
혹시 더 좋은 방법이 있다면, 방향을 제시해주시면 정말 감사할 것 같습니다.😥

2021-06-25 09:26 UTC, iborymagic commented on src/App.js
> +          <TimeLeft />
요부분에 관해서는 사실 해결 방법을 찾지 못하겠습니다.. 😥
여기서 컴포넌트로 더 묶는다거나 하기에는 아예 관련이 없는 컴포넌트들끼리만 남아버렸고,
조건문을 빼기에도 딱히 마땅한 방법이 떠오르지 않습니다.
혹시 방향을 제시해주실 수 있으신가요..? 😭

2021-06-25 09:28 UTC, iborymagic commented on src/contexts/ModalContextProvider.js
> +import React, { createContext, useState } from 'react';
value에다가 isModalOpen, setIsModalOpen을 넣은 것이 문제인지, 
아니면 openModal, closeModal이 포함된 것이 문제인지 잘 모르겠습니다.
openModal, closeModal은 사실 ModalContext에 포함되어도 딱히 어색함을 느끼지 못하겠는데,
혹시 추가적인 설명을 해주실 수 있으신가요?

2021-06-25 09:43 UTC, devJang commented on src/components/WinningNumber/index.js
> +    const inputValue = Math.min(Number(e.target.value), MAX_LOTTO_NUMBER);
`비제어 컴포넌트`에 `ref`까지 달려있던 컴포넌트로 보이던데
다음 번에는 `ref`를 달고 있으니 다른 방법으로 가져오는 것도 생각해보세요~

2021-06-25 09:54 UTC, devJang commented on src/contexts/ModalContextProvider.js
> +import React, { createContext, useState } from 'react';
제가 파일명을 잘못보고 코멘트를 달았네요~
잘 하셨습니다!

2021-06-25 09:59 UTC, devJang commented on src/components/LottoBallCanvas/index.js
> +  let isBallDrawn = false;
`useLottoBallCanvas()`로 분리하신 시도 보기 좋았습니다

힌트라면요.
정말 자세히 보면 외부함수로 유틸 성격으로 빼내서 반환값만 받는다던가
일반적인 `let` 선언 변수를 `useState`로 바꾸던가 이러한 방법들이 있을 것 같네요

일단 좋은 시도를 하셨기에 리팩터링에 좋은 한단계 왔다고 생각이 듭니다.

2021-06-25 16:55 UTC, iborymagic commented on src/components/LottoBallCanvas/index.js
> +  let isBallDrawn = false;
isBallDrawn이 렌더링을 유발하면 안되기 때문에 ref로 선언해서, 
해당 ref를 사용하는 함수들은 useLottoBallCanvas 내부에 남겨놓고, 아닌 함수는 service layer로 빼냈습니다.

useEffect에 모두 몰아넣는 게 딱히 비용적인 측면에서 잘못된지는 모르겠지만, 
한 곳에 너무 몰아넣으니 다른 코드들과 구별이 잘 되지 않는 것 같았습니다.
그래서 나머지 함수 선언들도 필요 변수들을 매개변수로 받도록 해서 useEffect 바깥으로 꺼내긴 했습니다.

옳은 방향의 리팩토링인지는 잘 모르겠네요.. 😭

2021-06-26 08:35 UTC, devJang commented on src/components/LottoBallCanvas/index.js
> +  let isBallDrawn = false;
좋습니다!
누구 만족시키자고 하는 리팩터링이 아니잖아요?

제가 제안드리는건 일단 분리하고 분리하는 것입니다.
또한 로또의 요구사항은 굉장히 작기때문에 이러한 문제가 나온다는 생각도 듭니다.
거기에 로또에 캔버스는 큰 요구사항이 아니고 직접 넣으신거니
일단 격리를 해보자는거죠!

로또의 관심사와 문제를 해결하시고 그것에 어느정도 만족이 되시면 그 다음 격리시킨 캔버스 로직을 분리하시는 것입니다.

옳은 방향의 리팩터링인지 모르겠으니 잘하신겁니다!
고생 많으셨구요

이제 옳은 방향을 설정하시는게 첫번째겠네요!

2021-06-26 08:42 UTC, devJang commented on src/App.js
> +          <TimeLeft />
`<React.Fragment>`로 감싼 녀석들을 다른 컴포넌트로 분리하는건 어떨까용?

2021-06-27 08:27 UTC, merged