[1단계 - 행운의 로또미션] 하루(김하루) 미션 제출합니다.
woowacourse/react-lotto pull request #8
Opened 2021-04-16 16:54 UTC by 365kim

__JBee님__, 안녕하세요!<br/>

오랜만에 인사드리는 🙋🏻‍♀️ 하루(@365kim) 입니다. 
지난 레벨1 때도 [로또 리뷰](https://github.com/woowacourse/javascript-lotto/pull/62)를 도와주셨었는데 요번에도 로또 미션으로 인사드리게 되었네요 ㅎㅎ
저는 주모(@jum0)과 함께 페어프로그래밍을 진행했습니다.

<br />

## 🎟 로또 미션 - 1단계 [데모 페이지](https://365kim.github.io/react-lotto/)
<p align="center"><img src="https://user-images.githubusercontent.com/60066472/115057537-25170400-9f1f-11eb-891b-a8b3138e6164.gif" width="600"></p>

## ✅ 구현 기능 목록
- 리액트 제한사항
  - [x] 클래스 컴포넌트를 사용한다.
- 구입금액 입력
  - [x] 로또 구입 금액을 입력하면, 유효성 검사 결과를 실시간으로 표시한다.
    - [x] 최소 화폐단위(1원) 미만의 자릿수가 포함된 경우
    - [x] 로또 1장의 가격(1,000원) 미만일 경우
    - [x] 로또 1장의 가격(1,000원)으로 나누어 떨어지지 않을 경우
- 로또 발급 및 확인
  - [x] 로또 구입 금액을 제출하면, 자동구매로 금액에 해당하는 로또를 발급한다.
  - [x] 번호보기 토글 버튼을 클릭하면 복권번호를 볼 수 있다.
- 당첨번호 발표
  - [x] 로또 발급 후 카운트 다운(3초)후에 이번주 당첨번호와 결과확인 버튼이 표시된다.
- 당첨결과 확인
  - [x] 결과 확인하기 버튼을 누르면 구매한 복권의 당첨여부 및 수익률을 모달로 표시된다.
    - [x] 로또 당첨 금액은 고정되어 있는 것으로 가정한다.
  - [x] 다시 시작하기 버튼을 누르면 초기화 되서 다시 구매를 시작할 수 있다.

## 💬 작성중
### 구현하면서 알쏭달쏭했던 부분 
### 새롭게 시도한 부분
### UX/UI고려사항

이번에도 크고 작은 개선사항 코멘트로 전해주시면 열심히 배우고 또 열심히 개선해보겠습니다..!!! 🙇🏻‍♀️🙇🏻‍♀️
감사합니다 😆

2021-04-16 18:13 UTC, 365kim commented on src/components/PurchaseLotto.js
> +            <Lotto numbers={v} key={String.fromCharCode(97 + i)} />
## 질문드립니다! 🙋🏻‍♀️  - 배열의 key값
`index`가 아닌 어떤 `key`를 사용할 수 있을지 고민스러웠습니다...🤔 
페어와 고민하다가`0, 1, 2, ...`를 `'a', 'b', 'c', ...`로 변환해봤는데 괜찮은 방법일지 혹은 추천해주시고 싶으신 더 일반적인(?) 방법이 있을지 궁금합니다.

2021-04-16 18:44 UTC, 365kim commented on src/constants/dummyData.json
> +}
인터넷에 공개된 동행복권 API를 사용할 생각으로 JSON형식으로 당첨번호 정보를 저장했습니다. 

\+ API에 접근은 가능한데 API 문서가 없어서 동행복권 측에 문의한 결과, 공식적으로 사용할 수 있는 API라는 답변을 얻었습니다...😢 아무리 널리 퍼져있더라도 공식적인 것은 아니다라는 교훈을 얻을 수 있었습니다,,

2021-04-17 08:17 UTC, JaeYeopHan commented on src/components/PurchaseLotto.js
> +            <Lotto numbers={v} key={String.fromCharCode(97 + i)} />
'key를 왜 넣어줘야 하는가?' 를 먼저 생각해보셔도 좋을 것 같네요?!

2021-04-17 09:14 UTC, JaeYeopHan requested changes
수고하셨습니다~ 코멘트 몇개 남겼어요!

기존 로또 프로젝트를 옮겨오지 말고 리액트 관점에 맞춰서 재정의하는 것이 더 좋을 것 같다는 생각이 들어요.
컴포넌트는 무엇인지, 어떤 단위로 나누어야 하는지도 같이 고민해봐요!

2021-04-17 09:14 UTC, jbee37142 commented on src/components/Animation.js
> +}
`<Animation/>`를 사용하는 쪽에서 `Lottie` 컴포넌트의 다른 props를 넘겨줘야 하는 경우가 발생한다면 넘겨주는 부분, 그리고 이 Animation 컴포넌트. 두 부분이 수정되어야 할 것 같은데, 문제점은 없는지 (있다면 어떻게 해결할 수 있을지) 고민해봐도 좋을 것 같아요!

2021-04-17 09:14 UTC, JaeYeopHan commented on src/components/PurchaseLotto.js
> +        <section className={`display-section ${this.state.isToggled && 'toggle'}`}>
`section`으로 한 이유가 있나요?

2021-04-17 09:14 UTC, JaeYeopHan commented on src/components/PurchaseLotto.js
> +            <input id="toggle-button" type="checkbox" onChange={this.onChangeToggleButton} />
이 부분은 왜 toggle-button 아이디로 스타일링 해줬는지 궁금합니다!
스타일링은 class로 제어한다 + BEM이라는 규칙으로 네이밍한다라는 것으로 연습해보셔도 좋을 것 같아요!

2021-04-17 09:14 UTC, JaeYeopHan commented on src/components/PurchaseLotto.js
> +          <label htmlFor="toggle-button" className="toggle-button-label">
label로 input element를 감싸주게 되면 for와 id를 연결해주지 않아도 됩니다!

2021-04-17 09:14 UTC, JaeYeopHan commented on src/components/PurchaseLotto.js
> +        <div>
`p`태그도 한번 고려해보시면 좋을 듯 하네요!

2021-04-17 09:14 UTC, JaeYeopHan commented on src/components/WinningResult.js
> +    return matchCount;
reduce로 바꿔봐도 좋을 것 같아요~

2021-04-17 09:14 UTC, JaeYeopHan commented on src/components/WinningResult.js
> +  getStatistics(matchCount) {
네이밍이 살짝 ㅎㅎ Statistics는 좀 제너럴한 느낌입니다!

2021-04-17 09:14 UTC, JaeYeopHan commented on src/components/WinningResult.js
> +      numOfMatch += BONUS_COUNT;
```suggestion
    const numOfMatch = lotto.reduce((acc, cur) => acc + Number(winningNumbers.includes(cur)), 0);

    if (numOfMatch === BONUS_CHECK_REQUIRED_COUNT && lotto.includes(bonusNumber)) {
      return numOfMatch + BONUS_COUNT;
```
은 어떨까요?

2021-04-17 09:14 UTC, JaeYeopHan commented on src/components/WinningResult.js
> +      shouldPlayAnimation: true,
역할이 많이 섞여있는 것 같아요!
이 애니메이션을 왜 실행시켜야 하는지를 기준으로 네이밍을 해봐도 좋을 것 같구요!

2021-04-17 09:49 UTC, 365kim commented on src/components/PurchaseLotto.js
> +            <Lotto numbers={v} key={String.fromCharCode(97 + i)} />
리액트에서 리스트를 만들 때 고유한 key를 설정하도록 강제하는 이유는 배열의 요소 추가, 수정, 삭제에 효율적으로 대응하기 위함으로 알고 있습니다. 
- __효율성 측면__
  - 예시: [a b c] 리스트에서 a를 삭제하여 [b c] 를 렌더할 경우, 
  - 문제: key값을 주지 않으면 a자리에 b를, b자리에 c를, c자리에는 아무것도 렌더하지 않는 번거로운 작업이 필요합니다.
  (key값을 주면 [a b c]에서 바로 a만 key값으로 잡아와서 빠르게 삭제할 수 있습니다.)
- __데이터 맵핑 측면__
  - 예시: [a b c] 리스트에서 a앞에 z를 추가하여 [z a b c] 를 렌더할 경우,
  - 문제: key값을 주지 않으면 리액트는 index를 default key값으로 활용하는데 이는 a(기존 index 0)가 가지고 있던 데이터가 z(새로운 index 0)에 맵핑되어 버립니다.([참고한 글](https://robinpokorny.medium.com/index-as-a-key-is-an-anti-pattern-e0349aece318))

두 가지 측면을 모두 생각해보았을 때 `고유한 key값을 가져야 한다`는 의미는 배열 내 `형제끼리 중복되지만 않으면 된다`라는 것 뿐만 아니라, `리렌더 되었을 때도 자신만의 고유한 key를 유지할 있어야 한다`는 의미로 이해했습니다. 🤔  제가 이해한 내용이 맞다면, index를 순차적으로 변환해서 `'a', 'b', 'c', ...`를 key값으로 주는 방식은 위의 데이터 맵핑이 꼬이는 문제를 전혀 해결할 수 없다고 생각됩니다. 따라서 리액트에서 필요로하는 key값을 주려면 nano id와 같은 id 생성기를 이용해야겠다고 생각했습니다.

그런데 [같은 글](https://robinpokorny.medium.com/index-as-a-key-is-an-anti-pattern-e0349aece318)에 따르면, 지금 제 경우처럼 리스트가 변하지 않고 정적일 것이 보장(재정렬, 필터되지 않음)되는 경우인데 딱히 쓸만한 id를 가진 것도 아닌 경우에는 굳이굳이 id를 생성하기 보다는 index를 key로 사용해도 좋다고 하고 있습니다...! 제가 생각해도 key가 꼭 필요한 상황이 아니어서 이런 경우에는 key값을 생략하려고 합니다..!

혹시 제가 잘못 생각한, 잘못 알고 있는 부분이 있다면 지적해주시면 감사하겠습니다 🙇🏻‍♀️

2021-04-17 09:59 UTC, 365kim commented on src/components/WinningResult.js
> +      shouldPlayAnimation: true,
```js
export default class DrawNumbers extends Component {
  constructor(props) {
   ...
    this.state = {
      shouldPlayAnimation: true,
    };
    this.destroyAnimation = this.destroyAnimation.bind(this);
  }

  componentDidMount() {
    setTimeout(this.destroyAnimation, COUNT_DOWN_ANIMATION_DURATION);
  }

  destroyAnimation() {
    this.setState({ shouldPlayAnimation: false });
  }
```
```js
export default class WinningResult extends Component {
  constructor(props) {
    ...
    this.state = {
     ...
      shouldPlayAnimation: true,
    };
    this.destroyAnimation = this.destroyAnimation.bind(this);
  }

  componentDidMount() {
    ...
    setTimeout(this.destroyAnimation, COIN_ANIMATION_DURATION);
  }

  destroyAnimation() {
    this.setState({ shouldPlayAnimation: false });
  }
```

현재 앱에서 2군데에서 애니메이션을 보여주고 있습니다. 애니메이션을 실행시키고 없애는 코드의 형태를 두 컴포넌트에서 동일하게 가져가고자 하는 의도로 네이밍했었습니다.
그런데 리뷰어님의 말씀을 듣고나니, 애니메이션의 내용이나 역할이 들어가는 네이밍이 더 적합하겠다는 생각이 이제야 듭니다...! 지금과 같은 네이밍이면, 컴포넌트 내에서 애니메이션 하나를 더 넣게되면 네이밍을 전부 다 수정해야할 것 같기도 하구요,,, 컴포넌트 내에서 역할에 어울리는 네이밍으로 좀 더 고민해보겠습니다. 감사합니다!👍

2021-04-17 10:06 UTC, 365kim commented on src/components/PurchaseLotto.js
> +          <label htmlFor="toggle-button" className="toggle-button-label">
지난 레벨1 로또미션 때 배웠던게 생각나서 label을 input으로 감싸기만 했었는데 아래와 같은 에러가 발생했습니다. 

'웹 표준 검사를 좀 강하게 하나보다'라는 짧은 생각으로 그냥 `for`와 `id`를 추가해주었는데, 지금 생각해보니 에러 로직이 잘못된게 아닌가하는 생각이 드네요...! 🤔  에러가 아닌데 에러라고 하는,,, 

그런데 `for`, `id`를 빼고 eslint config를 수정하거나, 이 한줄에 대해 해당 규칙을 적용시키지 않는 주석을 추가하는 것보다는 그냥 두는 것이 낫겠다고 생각되어서 요부분은 유지해보도록 하겠습니다...! 🙏

![image](https://user-images.githubusercontent.com/60066472/115109185-432c4500-9faf-11eb-9f67-f3ae3cab7bfb.png)

2021-04-17 10:08 UTC, 365kim commented on src/components/WinningResult.js
> +  getStatistics(matchCount) {
좀 더 어울리는 네이밍으로 고민해보겠습니다. 감사합니다! 😆

2021-04-17 10:23 UTC, 365kim commented on src/components/Animation.js
> +}
지금은 `<Animation/>`를 사용하는 모든 곳에서 각각 `height`, `speed`, `animationData`를 모두 전달하고 있습니다. 그런데 새로운 애니메이션에서는 `width`를 지정하고 싶어, 사용할 때 `width`를 지정한다면 `Animation` 컴포넌트 안에서 `<Lottie />`에서 `width={this.props.width}`를 다시 적어넣어 주어야 할 것입니다. 그런데 이미 `<Animation/>`을 사용하고 있던 측에서는 `width`를 지정하고 있지 않기 때문에 `undefined`값이 넘겨지는 문제가 생길 것 같습니다.

사용하는 측으로부터 무엇을 받든 `Animation`컴포넌트 안에서 알아서 쏘옥 `<Lottie />` 들어가는 식으로 가능하다면 처리해보고 싶은데.... 가능한지... 방법이 있는지 잘 모르겠습니다... 🥲  조금 더 고민해보겠습니다....! 좋은 피드백 감사드립니다 😆

2021-04-17 10:27 UTC, 365kim commented on src/components/PurchaseLotto.js
> +        <div>
네, 감사합니다!😆 말씀해주신 부분 이외에도 더 적합한 태그가 있는데 혹 그냥 복사해서 사용한 곳은 없는지 확인해보겠습니다!🥲

2021-04-17 10:29 UTC, 365kim commented on src/components/PurchaseLotto.js
> +        <section className={`display-section ${this.state.isToggled && 'toggle'}`}>
음... 사용자가 구매한 로또 티켓을 디스플레이 해주는 부분을 `<section>`으로 구역화할 수 있다고 생각하고 `<section>`을 사용했습니다. 그런데 전체적으로 검색해보니 `<section>` 태그는 보통 헤딩과 함께 헤더, 푸터, 또는 메인을 구성하는 큰 구획에 사용되는 것으로 확인했습니다...! 단락을 구분한다는 의미에서 위에서 추천해주신 `<p>` 태그로 변경해보겠습니다...! 감사합니다...!👍👍👍

2021-04-17 10:30 UTC, 365kim commented on src/components/WinningResult.js
> +      numOfMatch += BONUS_COUNT;
넘좋습니다...🥺🥺🥺  
`let`이 자꾸 저에게 자기 좀 없애달라고 말을 걸었는데... 제이비님 덕분에 `let`의 부탁을 들어줄 수 있게되었네욤 ㅎ_ㅎ 감사합니다...!!!

2021-04-17 10:38 UTC, 365kim commented on src/components/PurchaseLotto.js
> +            <input id="toggle-button" type="checkbox" onChange={this.onChangeToggleButton} />
원래는 className="toggle-button"으로 있던 것을 input이라 어차피 id가 필요하다면 그냥 class를 없앨까? 라는 짧은 생각으로 id에 스타일링을 해주었습니다. 똑같은 이름을 두 번 적는게 장황하게 느껴졌다는 이유입니다...🥲  요번 기회에 BEM으로 싹 적용해보면서 연습해보도록 하겠습니다! 좋은 지적 감사합니다 🙇🏻‍♀️🙇🏻‍♀️

\+ 쪼끔 바보같은 질문일 수 있지만 `id`가 아니라 `class`로만 스타일을 제어하는 것이 더 좋은 이유가 있을까용,,,?? 👉👈  제가 생각하는 장점은, CSS작성할 때 CSS 파일 내용이 .className 형태로 통일되서 전체적으로 깔끔해보인다는 점이나 jsx에서 className을 받고있다면 스타일링이 되고 있구나 라고 추론할 수 있는 것 정도.... 밖에 모르겠습니다,,,🥲  제가 놓친 이유가 있을지 궁금합니다..! 🙏

2021-04-18 08:52 UTC, JaeYeopHan commented on src/components/PurchaseLotto.js
> +            <Lotto numbers={v} key={String.fromCharCode(97 + i)} />
크

2021-04-18 08:53 UTC, JaeYeopHan commented on src/components/Animation.js
> +}
> 사용하는 측으로부터 무엇을 받든 Animation컴포넌트 안에서 알아서 쏘옥 <Lottie /> 들어가는 식으로 가능하다면 처리해보고 싶은데.... 가능한지... 

있어요! 화이팅!

2021-04-18 08:54 UTC, JaeYeopHan commented on src/components/PurchaseLotto.js
> +          <label htmlFor="toggle-button" className="toggle-button-label">
jsx-a11y lint에서 children를 고려하지 않고 validate해서 요런 에러가 발생해요 ㅎㅎ 웹 표준을 지키고 있지 않는 lint입니다 ㅋㅋㅋ

2021-04-18 14:47 UTC, 365kim commented
리뷰언님 안녕하세요 코멘트 남겨주신 것 보고 리팩토링 진행해봤습니다...! 💪

<br />

## 컴포넌트 설계 ✍🏻

✨컴포넌트✨는 비단 리액트에서뿐만 아니라 프로그래밍 전반에서 `재사용이 가능한 최소 단위`를 뜻하는 용어로 쓰인다고 알고있습니다. 

이번 PR 에서 총 4개의 컴포넌트를 만들었는데, 이 컴포넌트 들은 최상위 App 컴포넌트를 쪼개기 위한 `컨테이너` 정도의 역할을 하고 있었습니다. 재사용 가능한 컴포넌트가 `0개` 였습니다...! (뜨헉)

재사용 가능한 컴포넌트를 만들자는 목적으로 리팩토링을 시작했습니다. 🚀  최상위 컴포넌트에 가까울수록 도메인 로직이 많이 들어가서 재사용할 수 있게 만들기 어렵지만, 하위 컴포넌트로 내려오면 좀 더 재사용 가능한 컴포넌트를 뽑아내기 쉬울 것이라고 생각했습니다.

그래서 우선, `컨테이너(containers)` 역할을 하는 컴포넌트와 `재사용 가능한(shared)` 컴포넌트를 분리하는 방향으로 폴더 구조를 변경하였습니다. 

`./containers`는 App 바로 밑의 큼직 큼직한 컴포넌트를, `./shared`에는 재사용되는 컴포넌트를 배치했습니다. 컨테이너가 너무 크기 때문에 분리하려는 목적으로 만든, 재사용되지 않는 컴포넌트의 경우에는 해당 컨테이너 하위에 별도의 모듈로 분리했습니다. 덧붙여, 각 컨테이너에서 필요한 로직을 수행해주는 service.js를 추가했습니다.

한편, 앱 내에서 여러 컴포넌트에 걸쳐 사용되고 있다면 도메인과 연관이 있더라도 `./shared`에 배치했습니다. 이름 상으로는 `<PlainButton />` `<ToggleButton /> `등 모든 버튼이 `<Button />`을 상속받게 해야할 것 같은데 그 안의 필요한 속성과 스타일이 서로 다 달라 보여서, 상속 받는게 어떤 의미가 있을지 모르겠다고 생각했습니다. 그래서 `<Button />`을 따로 만들지 않고 그대로 두게 되었습니다.

수십 개의 파일을 수정하면서 나름 대공사를 거쳤는데, 목적대로 재사용성이 높아진건지 잘 모르겠...습니다...🥲 분명 이전의 4개의 왕컴포넌트 보다는 낫겠지만... 한번 보시고 피드백 주시면 감사하겠습니다...!! 🙇🏻‍♀️🙇🏻‍♀️

```
components
┣ App 
┃
┣ containers
┃ ┣ PurchaseForm
┃ ┣ UserLotto
┃ ┃ ┗ Lotto
┃ ┃ WinningNumbers
┃ ┃ ┗ WinningNumberList
┃ ┗ UserResult
┃   ┣ ResultSummary
┃   ┗ ResultTable
┃  
┗ shared
   ┣ Animation
   ┣ PlainButton
   ┣ SubmitButton
   ┣ ToggleButton
   ┣ XButton
   ┣ LottoBall
   ┗ TwoDigitBal

```

2021-04-18 14:59 UTC, 365kim commented
## 📌 리뷰반영 요약표
| 번호 | 리뷰내용 |관련코멘트 | 반영커밋 | 
|:---:|:---|:---:|:---|
|1| 컴포넌트 단위 다시 생각해보기! <br>👉 폴더구조 변경 및 shared 컴포넌트 생성  | [바로가기](https://github.com/woowacourse/react-lotto/pull/8#pullrequestreview-638209383) | 4ff87ad | 
|2| 배열의 key값 넣어주는 의미 다시 생각해보기! <br>👉 재정렬 되지 않는 배열에는 기본값인 index를 key값으로 활용 | [바로가기](https://github.com/woowacourse/react-lotto/pull/8#discussion_r615038405) | 30b056d | 
|3| props 스마트하게 전달받기! <br> 👉 \<Lottie /\> props 스프레드로 전달 | [바로가기](https://github.com/woowacourse/react-lotto/pull/8#discussion_r615226073) | 46f94bd | 
|4| 더 깔끔하게 메서드 작성! <br> 👉 reduce 활용, let 제거 | [바로가기](https://github.com/woowacourse/react-lotto/pull/8#discussion_r615230406) | 1ee3b01  be11367 | 
|5| 태그 선택에 유의! <br> 👉 적절하지 않은 \<section\> 태그 대신 \<p\> 태그 적용 | [바로가기](https://github.com/woowacourse/react-lotto/pull/8#discussion_r615230289) | 4551a99 | 
|6| 스타일링은 class로 제어! <br> 👉 BEM 네이밍 적용 | [바로가기](https://github.com/woowacourse/react-lotto/pull/8#discussion_r615230175) | e2f6bb1 | 
|7| 더 적합한 네이밍으로! <br> 👉 getStatistics -> getComputedResult으로 변경 <br> 👉shouldPlayAnimation -> isLoading 으로 변경 | [바로가기](https://github.com/woowacourse/react-lotto/pull/8#discussion_r615230863) | 911aaf7, a35218f |

2021-04-18 15:03 UTC, JaeYeopHan commented on src/components/PurchaseLotto.js
> +            <input id="toggle-button" type="checkbox" onChange={this.onChangeToggleButton} />
id는 재사용이 안 됩니다!

2021-04-18 15:04 UTC, 365kim commented on src/components/PurchaseLotto.js
> +            <input id="toggle-button" type="checkbox" onChange={this.onChangeToggleButton} />
🔖 [getbem](http://getbem.com/naming/), [에어비앤비 CSS 스타일가이드](https://github.com/airbnb/css#oocss-and-bem) 
두 레퍼런스를 참조해서 BEM 네이밍을 적용해 보았습니다!

📌 관련 커밋: e2f6bb1

2021-04-18 15:05 UTC, JaeYeopHan commented on src/components/shared/PlainButton/index.js
> +    );
```suggestion
    const { className, text, ...props } = this.props;

    return (
      <button type="button" className={`PlainButton ${className}`} {...props}>
        {text}
      </button>
    );
```
어때요?

2021-04-18 15:07 UTC, JaeYeopHan commented on src/components/shared/PlainButton/index.js
> +export default class PlainButton extends Component {
이름이 `PlainButton`인 이유는 `type`이 button이어서 그런건가요???

보통 Button은 스타일을 목적으로 재사용을 하게 될텐데, type도 props로 custom할 수 있도록 해보면 어떨까요?
컴포넌트에 대한 시야를 빠르게 확보할 수 있는 방법 중 첫번째는 잘 맨들어진 오픈소스 디자인 시스템을 보는 것입니다! (cc. https://chakra-ui.com/docs/form/button <- 제가 좋아하는 챠크라 UI 소개드려봐용)
두번째는 객체 지향의 책임과 역할 공부하기 인데요, 요건 천천히 해보셔도 좋을 것 같아요!

2021-04-18 15:09 UTC, JaeYeopHan commented on src/components/shared/TwoDigitBall/index.js
> +    const numberText = number < 10 ? `0${number}` : number;
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

2021-04-18 15:10 UTC, JaeYeopHan commented on src/components/shared/TwoDigitBall/index.js
> +    return <span className={`TwoDigitBall ${className}`}>{numberText}</span>;
https://github.com/JedWatson/classnames

2021-04-18 15:10 UTC, 365kim commented on src/components/shared/TwoDigitBall/index.js
> +    const numberText = number < 10 ? `0${number}` : number;
앗 내장 메서드가 있었군요...! 🥺 바로 적용해보겠습니당!! 감사합니다..!! 🙏

2021-04-18 15:11 UTC, JaeYeopHan commented on src/components/shared/ToggleButton/index.js
> +    const { onChange, text } = this.props;
```suggestion
    const { onChange, children } = this.props;
```

어때요?

2021-04-18 15:12 UTC, JaeYeopHan commented on src/components/shared/SubmitButton/index.js
> +      </button>
```suggestion
    const { className, disabled, children } = this.props;

    return (
      <button type="submit" className={`SubmitButton ${className}`} disabled={disabled}>
        {children}
      </button>
```

어때요?

2021-04-18 15:12 UTC, 365kim commented on src/components/shared/TwoDigitBall/index.js
> +    return <span className={`TwoDigitBall ${className}`}>{numberText}</span>;
오와오!!!!! 대박스 바로 설치해서 적용해보겠습니다! 제이비님 꿀벌이셨군요,,, 꿀팁에서 꿀이 쥬르르...🍯💙

2021-04-18 15:14 UTC, 365kim commented on src/components/shared/ToggleButton/index.js
> +    const { onChange, text } = this.props;
`text`보다 `children`이 더 범용적으로 쓰일 수 있어서 훨씬 좋은 것 같습니다!! 이제야 text가 아니라 컴포넌트가 통째로 들어갈 수도 있겠다 싶습니당,, 시야가 확장되는 느낌입니다...! 좋은 피드백 감사드립니다! 😆 👍

2021-04-18 15:14 UTC, JaeYeopHan commented on src/components/containers/UserResult/ResultSummary.js
> +        </p>
저라면 요 단위를 컴포넌트화 해볼 것 같아요!
`Record`라는 이름으로요!
`ResultSummary`라는 컴포넌트가 재사용될까요? 🤔 

```suggestion
        <p className="record">
          <span className="record-label">{label}</span>
          <span className="record-value">{children}</span>
        </p>
```

2021-04-18 15:18 UTC, JaeYeopHan commented on src/components/Animation.js
> +}
cc https://github.com/woowacourse/react-lotto/pull/8#discussion_r615411595

2021-04-18 15:21 UTC, 365kim commented on src/components/shared/PlainButton/index.js
> +export default class PlainButton extends Component {
제가 작성한 `<PlainButton />`가 제가 생각하는 (기본 중의 기본이 되는) `<Button />`의 모습이 아니기 때문에 Button이라는 이름을 자신있게 주지 못했습니다...👉👈
![image](https://user-images.githubusercontent.com/60066472/115150697-7dc3d980-a0a4-11eb-92fb-bd32944f779b.png)
처음에 props로 줬을 때 위와 같은 에러를 만났습니다... 
필요하면 eslint 설정을 바꾸고 의도한 대로 코드를 작성해야 하는데 에러를 안보겠다는 짧은 생각으로 바로 리터럴로 넣어주었습니다...🥲  반성합니다,,,, 🥲 `type`도 `props`로 받도록 하고, 공유해주신 레퍼런스 참고해서 좀 더 컴포넌트스러운 `<Button />`으로 만들어보도록 하겠습니다!! `객체지향의 책임과 역할`키워드도 잊지않고 틈나는 대로 학습해보겠습니다!!! 💪💪 감사합니다

2021-04-18 15:30 UTC, 365kim commented on src/components/containers/UserResult/ResultSummary.js
> +        </p>
오어... 이거였습니다... 제가 하고싶었던게🤩 이렇게 누가봐도 재사용할 수 있을 것 같은 컴포넌트였는데... 현실은...🥲`ResultSummary`는 상위 컨테이너가 장황해져서 쪼개려는 목적으로 분리하게 되었습니다...! 위에 공유해주셨던 챠크라의 컴포넌트 천천히 살펴보고, 단순히 쪼개는 것보다 재사용성을 좀 더 고민하면서 이렇게 재사용 가능한 컴포넌트를 늘려보겠습니다!! 정말정말 시야가 트이는 느낌이에요! 감사합니다~🙇🏻‍♀️😆🙇🏻‍♀️

2021-04-18 16:33 UTC, JaeYeopHan commented on src/components/containers/UserResult/ResultSummary.js
> +        </p>
단순 추출이 아닌, 의존성을 기반으로 추상화하는 연습을 해조시면 좋을 것 같아요! 높은 응집도 + 낮은 결합도!

어려운 말들이고 저도 계속 연습하고 있는 부분입니다 💪

2021-04-18 16:42 UTC, 365kim commented on src/components/containers/UserResult/ResultSummary.js
> +        </p>
1단계 제한사항이 클래스 컴포넌트를 사용하는 것이라서 클래스 컴포넌트로 반영해보았습니다..!

📌 관련커밋: 61ff42a

2021-04-18 17:27 UTC, 365kim commented on src/components/containers/UserResult/ResultSummary.js
> +        </p>
앗 코멘트를 이제봤네요...! `높은 응집도 + 낮은 결합도` 유념해서 도전해보겠습니다!! 🚀🚀🚀🚀 감사합니다! 💙

2021-04-19 02:03 UTC, JaeYeopHan commented on src/components/shared/Button/index.js
> +      </button>
1. children 그대로 넘겨주면 되겠는데요?
2. className에 아무 것도 안 넘긴다면?

```suggestion
    const { className, ...props } = this.props;
    const buttonClass = cx(className, Button);

    return (
      <button className={buttonClass} {...props} />
```

2021-04-19 02:04 UTC, JaeYeopHan approved these changes
수고하셨어요!ㅎㅎ
일부러 빡세게 리뷰했는데, 너무 빡빡했다면 피드백 해주세요!

코멘트 하나 살짝 추가해봤어요~ (https://github.com/woowacourse/react-lotto/pull/8/files#r615501370)

2021-04-19 02:04 UTC, merged

2021-04-19 02:13 UTC, 365kim commented on src/components/shared/Button/index.js
> +      </button>
앗 조건부 아니고 항상 넣어줄거면 심플하게 인자로 넣어주면 되는거였군요! [리드미](https://github.com/JedWatson/classnames#classnames)에 Syntax 다시 읽고왔습니당ㅎㅎ 감사합니다!
```js
classNames('foo', 'foo', 'bar'); // => 'foo bar'
classNames('foo', { foo: false, bar: true }); // => 'bar'
```

2021-04-19 02:33 UTC, 365kim commented on src/components/shared/Button/index.js
> +      </button>
말씀해주신 것처럼 `children`을 `...props`에 한꺼번에 넣을 경우 JSX가 어떻게 처리되는지 아직 머릿 속에 잘 안그려져서 Babel에 적어봤습니다..!

```js
// children을 따로 빼서 넘겨주는 경우
<button className={buttonClass} {...props}>
  {children}
</button>
```
```js
// 트랜스파일 후
export default class Button extends Component {
  render() {
    const { className, children, ...props } = this.props;
    const buttonClass = cx(className, "Button");
    return /*#__PURE__*/ React.createElement(
      "button",
      _extends(
        {
          className: buttonClass
        },
        props
      ),
      children
    );
  }
}
```


```js
// children을 ...props에 포함시켜넣거나 props와 같은 위계(?)에서 넘겨주는 경우
<button className={buttonClass} children={children} {...props} />
```
```js
// 트랜스파일 후
export default class Button extends Component {
  render() {
    const { className, children, ...props } = this.props;
    const buttonClass = cx(className, "Button");
    return /*#__PURE__*/ React.createElement(
      "button",
      _extends(
        {
          className: buttonClass,
          children: children
        },
        props
      )
    );
  }
}
```
두 경우에 트랜스파일링 후 children이 들어가는 위치가 다르게 보이고, [React.createElement API](https://ko.reactjs.org/docs/react-api.html#createelement)에서 세번째 인자를 children로 넣어주고 있어서 두번째 인자에 한번에 `...props`로 보내도 괜찮을까 싶었는데 실행시켜 보니까 잘되네요,,,,?,,,,,👉👈  

요것이 이해가 안되는 건 제가 JS문법 기초가 부족해서일까요,,,🥲  어떻게 이해하면 좋을지 조언해주시면 매우매우 감사하겠습니다,,, 🙏

2021-04-19 02:35 UTC, 365kim commented on src/components/shared/Button/index.js
> +      </button>
className에 아무것도 안넘긴다면 `undefined`: true가 되고 있었군요...! 수정해주신대로 하면 classnames가 알아서 처리해주니 문제 없겠네요! 감사합니다 😆

2021-04-19 02:46 UTC, 365kim commented on src/components/shared/Button/index.js
> +      </button>
제 로컬에 설치된 코드 스펠링 체크해주는 익스텐션 `cspell`에서 밑줄뜨면 별 생각없이 수정했는데, 필요할 경우 `user dictionary`에 추가하거나 `cspell.json`에서 설정을 작성자가 필요한대로 바꿀 수 있다는 사실을 알게되었습니다! ([참고문서](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)) `classnames`외에도 추가할 단어들이 있을 것 같고, 이 설정 파일도 push해놓는게 좋을 것 같아서 cspell.json에서 관리해보려고 합니당! 에디터에 `cspell`때문에 PROBLEM 몇십 개 줄줄이 뜨곤 했는데...(못본 척했지만...🥲) 이제  없앨 수 있게되었네요~~~😆